[package]
name = "pagliascii"
version = "0.1.0"
authors = ["Lukas Wirth <lukastw97@gmail.com>"]
edition = "2018"

[dependencies]
nom = "6.1.0"
nom_locate = "3.0.0"
indexmap = "1.6.1"

[dev-dependencies]
expect-test = "1.1.0"
